### ISSUE TITLE
Android Compatibility 

### ISSUE THREAD

**Issue by kakaiser** [asciidisco/plugin.video.telekom-sport#1]
Hi,
When trying to install I get error message 

06:43:42.930 T:18446744071930738992   ERROR: Previous line repeats 1 times.
06:43:42.930 T:18446744071930738992   ERROR: CAddonInstallJob[plugin.video.telekom-sport]: Die Abhängigkeit auf script.module.pydes in Version 2.0.1 konnte nicht aufgelöst werden.

Kodi 17.3 auf Android 6.01

**Comment by asciidisco** [comment]
The missing dependency can be found here: https://github.com/kodinerds/repo/raw/master/script.module.pydes/script.module.pydes-2.0.1.zip
Install it & restart Kodi & it should work.

I´ll refactor that one out in the future & handle the encryption of userdata with Python internal methods.

**Comment by asciidisco** [comment]
Fixed in version 1.2.3
